/**
 * DEV ONLY — seed a synthetic snapshot for local UI work without hitting EDGAR.
 *
 * In production, snapshots are generated by `npm run ingest` (live EDGAR feed).
 * This script is kept around purely for local dev convenience when iterating
 * on the UI without touching the network. It will FAIL noisily if accidentally
 * invoked in CI to prevent demo data from sneaking into production.
 *
 *   npm run seed   <-- script removed; invoke manually:
 *   tsx scripts/seed-snapshot.ts
 */

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { buildSeedHistory, buildSeedTransactions } from "../lib/seed";
import { buildSnapshot } from "../lib/snapshot";

if (process.env.CI === "true") {
  console.error("seed-snapshot.ts must NOT run in CI. Use `npm run ingest` instead.");
  process.exit(1);
}

const OUT_DIR = join(process.cwd(), "data");
const OUT_FILE = join(OUT_DIR, "insider-snapshot.json");

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const generatedAt = new Date().toISOString();
const txs = buildSeedTransactions(generatedAt);
const snapshot = buildSnapshot(txs, {
  generatedAt,
  windowDays: 7,
  clusterWindowDays: 30,
  clusterMinInsiders: 3,
  isDemo: true,
});
snapshot.history = buildSeedHistory(generatedAt, snapshot.index);

writeFileSync(OUT_FILE, JSON.stringify(snapshot, null, 2));
console.warn("⚠ Wrote SEED snapshot — DEV ONLY, do not commit to main.");
console.log(`  ${OUT_FILE}`);
console.log(`  Index: ${snapshot.index} (${snapshot.phase})`);
